name: "Build a manylinux wheel"

on:
  push:
    branches:
      - manylinux-release

jobs:
  build-wheel:
    name: Build manylinux wheel
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt-get install -y wget software-properties-common wget lsb-release gnupg
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
          sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get install cmake g++-11
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 90
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 90

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg && ./bootstrap-vcpkg.sh
          echo "VCPKG_ROOT=${{github.workspace}}/vcpkg" >> $GITHUB_ENV
          echo "${{github.workspace}}/vcpkg" >> $GITHUB_PATH
          ./vcpkg integrate install

      - name: Install dependencies
        run: python -m pip install -U pip "pybind11[global]" cmake build

      - name: Build
        run: python -m build -o dist

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-20.04 wheel
          path: ${{github.workspace}}/dist/*.whl
